[project]
name = "trone-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "sqlalchemy>=2.0.40",
    "sqlalchemy-orm>=1.2.10",
    "tronpy>=0.5.0",
]
